#!/usr/bin/env bun
/**
 * analyze-complex - Auto-generated skill script
 * Generated by Engram from pattern: 477c9c94-e6e4-4a67-9316-92ec0b157bde
 *
 * Deep architectural exploration skill that systematically reads and analyzes complex cognitive or meta-cognitive system implementations before development work.
 */

import { $ } from "bun";

// Parse arguments
const args = process.argv.slice(2);
const targetDir = args[0] || process.cwd();

console.log(`Running ${skill.name} in ${targetDir}`);

async function step1() {
  const result = await $`ls -la ${targetDir}`.text();
  console.log(result);
}

async function step2() {
  const filePath = `${targetDir}/synthesis.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step3() {
  const filePath = `${targetDir}/thesis.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step4() {
  const filePath = `${targetDir}/antithesis.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step5() {
  const glob = new Bun.Glob("scripts/**/*.ts");
  const files = Array.from(glob.scanSync(targetDir));
  console.log(`Found ${files.length} files matching scripts/**/*.ts`);
  return files;
}

async function step6() {
  const glob = new Bun.Glob("src/**/*.ts");
  const files = Array.from(glob.scanSync(targetDir));
  console.log(`Found ${files.length} files matching src/**/*.ts`);
  return files;
}

async function step7() {
  const filePath = `${targetDir}/index.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step8() {
  const filePath = `${targetDir}/encoder.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step9() {
  const filePath = `${targetDir}/index.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step10() {
  const filePath = `${targetDir}/index.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step11() {
  const filePath = `${targetDir}/retriever.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step12() {
  const filePath = `${targetDir}/retriever.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step13() {
  const filePath = `${targetDir}/encoder.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step14() {
  const filePath = `${targetDir}/syntactic.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step15() {
  const filePath = `${targetDir}/index.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step16() {
  const filePath = `${targetDir}/thesis.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step17() {
  const filePath = `${targetDir}/index.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step18() {
  const filePath = `${targetDir}/antithesis.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step19() {
  const filePath = `${targetDir}/index.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step20() {
  const filePath = `${targetDir}/short-term.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step21() {
  const filePath = `${targetDir}/validator.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step22() {
  const filePath = `${targetDir}/encoder.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step23() {
  const filePath = `${targetDir}/package.json`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step24() {
  const filePath = `${targetDir}/user-prompt-submit.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step25() {
  const filePath = `${targetDir}/script-generator.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function main() {
  try {
    console.log("Step 1: Execute ls");
    await step1();
    console.log("Step 2: Read file /Users/chietala/Code/engram/src/dialectic/synthesis.ts");
    await step2();
    console.log("Step 3: Read file /Users/chietala/Code/engram/src/dialectic/thesis.ts");
    await step3();
    console.log("Step 4: Read file /Users/chietala/Code/engram/src/dialectic/antithesis.ts");
    await step4();
    console.log("Step 5: Find files matching scripts/**/*.ts");
    await step5();
    console.log("Step 6: Find files matching src/**/*.ts");
    await step6();
    console.log("Step 7: Read file /Users/chietala/Code/engram/src/llm/index.ts");
    await step7();
    console.log("Step 8: Read file /Users/chietala/Code/engram/src/memory/processing/encoder.ts");
    await step8();
    console.log("Step 9: Read file /Users/chietala/Code/engram/src/embedding/index.ts");
    await step9();
    console.log("Step 10: Read file /Users/chietala/Code/engram/src/dialectic/index.ts");
    await step10();
    console.log("Step 11: Read file /Users/chietala/Code/engram/src/memory/processing/retriever.ts");
    await step11();
    console.log("Step 12: Read file /Users/chietala/Code/engram/src/memory/processing/retriever.ts");
    await step12();
    console.log("Step 13: Read file /Users/chietala/Code/engram/src/memory/processing/encoder.ts");
    await step13();
    console.log("Step 14: Read file /Users/chietala/Code/engram/src/stages/syntactic.ts");
    await step14();
    console.log("Step 15: Read file /Users/chietala/Code/engram/src/embedding/index.ts");
    await step15();
    console.log("Step 16: Read file /Users/chietala/Code/engram/src/dialectic/thesis.ts");
    await step16();
    console.log("Step 17: Read file /Users/chietala/Code/engram/src/skill-generator/index.ts");
    await step17();
    console.log("Step 18: Read file /Users/chietala/Code/engram/src/dialectic/antithesis.ts");
    await step18();
    console.log("Step 19: Read file /Users/chietala/Code/engram/src/stages/index.ts");
    await step19();
    console.log("Step 20: Read file /Users/chietala/Code/engram/src/memory/short-term.ts");
    await step20();
    console.log("Step 21: Read file /Users/chietala/Code/engram/src/skill-generator/validator.ts");
    await step21();
    console.log("Step 22: Read file /Users/chietala/Code/engram/src/memory/processing/encoder.ts");
    await step22();
    console.log("Step 23: Read file /Users/chietala/Code/engram/package.json");
    await step23();
    console.log("Step 24: Read file /Users/chietala/Code/engram/src/hooks/user-prompt-submit.ts");
    await step24();
    console.log("Step 25: Read file /Users/chietala/Code/engram/src/skill-generator/script-generator.ts");
    await step25();

    console.log("\nCompleted successfully");
  } catch (error) {
    console.error("Failed:", error);
    process.exit(1);
  }
}

main();