#!/usr/bin/env bun
/**
 * explore-codebase-8 - Auto-generated skill script
 * Generated by Engram from pattern: 477c9c94-e6e4-4a67-9316-92ec0b157bde
 *
 * Performs adaptive codebase exploration that transitions from breadth-first reconnaissance to depth-first investigation as relevant files are discovered.
 */

import { $ } from "bun";

// Parse arguments
const args = process.argv.slice(2);
const targetDir = args[0] || process.cwd();

console.log(`Running ${skill.name} in ${targetDir}`);

async function step1() {
  const result = await $`find ${targetDir} -type f -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" -o -name "*.json" | head -20`.text();
  console.log(result);
}

async function step2() {
  const result = await $`ls -la ${targetDir}`.text();
  console.log(result);
}

async function step3() {
  const result = await $`find ${targetDir} -type f -name "*.ts" | grep -E "(conceptual|semantic)" | head -5`.text();
  console.log(result);
}

async function step4() {
  const filePath = `${targetDir}/README.md`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step5() {
  const result = await $`find ${targetDir} -type f -name "*.ts" -o -name "*.tsx" | head -20`.text();
  console.log(result);
}

async function step6() {
  const result = await $`ls -la ${targetDir} 2>/dev/null || find ${targetDir} -type d -name "skill-generator" 2>/dev/null`.text();
  console.log(result);
}

async function step7() {
  const glob = new Bun.Glob("src/db/queries/patterns.ts");
  const files = Array.from(glob.scanSync(targetDir));
  console.log(`Found ${files.length} files matching src/db/queries/patterns.ts`);
  return files;
}

async function step8() {
  const glob = new Bun.Glob("/Users/chietala/Code/engram/src/db/queries/*.ts");
  const files = Array.from(glob.scanSync(targetDir));
  console.log(`Found ${files.length} files matching /Users/chietala/Code/engram/src/db/queries/*.ts`);
  return files;
}

async function step9() {
  const filePath = `${targetDir}/patterns.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step10() {
  const filePath = `${targetDir}/dialectic.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step11() {
  const result = await $`find ${targetDir} -name "*.test.ts" -o -name "*.spec.ts" | head -10`.text();
  console.log(result);
}

async function step12() {
  const result = await $`find ${targetDir} -name "*.test.ts" -o -name "*.spec.ts" 2>/dev/null`.text();
  console.log(result);
}

async function step13() {
  const result = await $`grep -r "pattern\\.name|\\.name =|pattern-name" ${targetDir}`.text().catch(() => "");
  console.log(result || "No matches found");
  return result;
}

async function step14() {
  const result = await $`find ${targetDir} -type f -name "SKILL.md" 2>/dev/null | head -10`.text();
  console.log(result);
}

async function step15() {
  const result = await $`ls -la ${targetDir} 2>/dev/null | head -20`.text();
  console.log(result);
}

async function step16() {
  const filePath = `${targetDir}/SKILL.md`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step17() {
  const filePath = `${targetDir}/SKILL.md`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function step18() {
  const result = await $`find ${targetDir} -name "*.db" -type f 2>/dev/null`.text();
  console.log(result);
}

async function step19() {
  const filePath = `${targetDir}/index.ts`;
  const content = await Bun.file(filePath).text();
  console.log(`Read ${content.length} bytes from ${filePath}`);
  return content;
}

async function main() {
  try {
    console.log("Step 1: Execute find");
    await step1();
    console.log("Step 2: Execute ls");
    await step2();
    console.log("Step 3: Execute find");
    await step3();
    console.log("Step 4: Read file /Users/chietala/Code/engram/README.md");
    await step4();
    console.log("Step 5: Execute find");
    await step5();
    console.log("Step 6: Execute ls");
    await step6();
    console.log("Step 7: Find files matching src/db/queries/patterns.ts");
    await step7();
    console.log("Step 8: Find files matching /Users/chietala/Code/engram/src/db/queries/*.ts");
    await step8();
    console.log("Step 9: Read file /Users/chietala/Code/engram/src/db/queries/patterns.ts");
    await step9();
    console.log("Step 10: Read file /Users/chietala/Code/engram/src/db/queries/dialectic.ts");
    await step10();
    console.log("Step 11: Execute find");
    await step11();
    console.log("Step 12: Execute find");
    await step12();
    console.log("Step 13: Search for pattern\.name|\.name =|pattern-name");
    await step13();
    console.log("Step 14: Execute find");
    await step14();
    console.log("Step 15: Execute ls");
    await step15();
    console.log("Step 16: Read file /Users/chietala/Code/engram/.claude/skills/grep-bash-pattern/SKILL.md");
    await step16();
    console.log("Step 17: Read file /Users/chietala/Code/engram/.claude/skills/read-bash-pattern-1/SKILL.md");
    await step17();
    console.log("Step 18: Execute find");
    await step18();
    console.log("Step 19: Read file /Users/chietala/Code/engram/src/worker/index.ts");
    await step19();

    console.log("\nCompleted successfully");
  } catch (error) {
    console.error("Failed:", error);
    process.exit(1);
  }
}

main();